// <auto-generated />
using System;
using Intuit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intuit.Api.Migrations
{
    [DbContext(typeof(IntuitDBContext))]
    [Migration("20250911002204_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intuit.Api.Domain.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Address");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BirthDate");

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Cuit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Mobile");

                    b.HasKey("ClientId");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Calle Falsa 123",
                            BirthDate = new DateOnly(1990, 5, 12),
                            Cuit = "27-12345678-5",
                            Email = "ana@example.com",
                            FirstName = "Ana",
                            LastName = "García",
                            Mobile = "+5491122334455"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "Av. Siempreviva 742",
                            BirthDate = new DateOnly(1985, 4, 8),
                            Cuit = "20-11111111-9",
                            Email = "luis@example.com",
                            FirstName = "Luis",
                            LastName = "Pérez",
                            Mobile = "+5491144455566"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Belgrano 101",
                            BirthDate = new DateOnly(1988, 7, 1),
                            Cuit = "20-22222222-3",
                            Email = "carlos@example.com",
                            FirstName = "Carlos",
                            LastName = "López",
                            Mobile = "+5491100000003"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Mitre 220",
                            BirthDate = new DateOnly(1992, 3, 22),
                            Cuit = "27-23456789-2",
                            Email = "maria@example.com",
                            FirstName = "María",
                            LastName = "Fernández",
                            Mobile = "+5491100000004"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Rivadavia 330",
                            BirthDate = new DateOnly(1991, 9, 14),
                            Cuit = "20-33333333-6",
                            Email = "julian@example.com",
                            FirstName = "Julián",
                            LastName = "Martínez",
                            Mobile = "+5491100000005"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Sarmiento 450",
                            BirthDate = new DateOnly(1993, 1, 5),
                            Cuit = "27-34567890-1",
                            Email = "sofia@example.com",
                            FirstName = "Sofía",
                            LastName = "Rodríguez",
                            Mobile = "+5491100000006"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "San Martín 512",
                            BirthDate = new DateOnly(1987, 11, 2),
                            Cuit = "20-44444444-8",
                            Email = "pedro@example.com",
                            FirstName = "Pedro",
                            LastName = "Sánchez",
                            Mobile = "+5491100000007"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "Alsina 600",
                            BirthDate = new DateOnly(1995, 6, 30),
                            Cuit = "27-45678901-0",
                            Email = "lucia@example.com",
                            FirstName = "Lucía",
                            LastName = "Gómez",
                            Mobile = "+5491100000008"
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "Urquiza 710",
                            BirthDate = new DateOnly(1989, 10, 18),
                            Cuit = "20-55555555-5",
                            Email = "diego@example.com",
                            FirstName = "Diego",
                            LastName = "Torres",
                            Mobile = "+5491100000009"
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "Moreno 820",
                            BirthDate = new DateOnly(1994, 2, 27),
                            Cuit = "27-56789012-8",
                            Email = "valentina@example.com",
                            FirstName = "Valentina",
                            LastName = "Díaz",
                            Mobile = "+5491100000010"
                        },
                        new
                        {
                            ClientId = 11,
                            Address = "Lavalle 930",
                            BirthDate = new DateOnly(1986, 12, 9),
                            Cuit = "20-66666666-1",
                            Email = "matias@example.com",
                            FirstName = "Matías",
                            LastName = "Romero",
                            Mobile = "+5491100000011"
                        },
                        new
                        {
                            ClientId = 12,
                            Address = "Catamarca 1040",
                            BirthDate = new DateOnly(1990, 8, 3),
                            Cuit = "27-67890123-6",
                            Email = "camila@example.com",
                            FirstName = "Camila",
                            LastName = "Ruiz",
                            Mobile = "+5491100000012"
                        },
                        new
                        {
                            ClientId = 13,
                            Address = "Córdoba 1150",
                            BirthDate = new DateOnly(1983, 4, 16),
                            Cuit = "20-77777777-7",
                            Email = "fernando@example.com",
                            FirstName = "Fernando",
                            LastName = "Gutiérrez",
                            Mobile = "+5491100000013"
                        },
                        new
                        {
                            ClientId = 14,
                            Address = "Tucumán 1260",
                            BirthDate = new DateOnly(1991, 1, 25),
                            Cuit = "27-78901234-4",
                            Email = "paula@example.com",
                            FirstName = "Paula",
                            LastName = "Silva",
                            Mobile = "+5491100000014"
                        },
                        new
                        {
                            ClientId = 15,
                            Address = "Salta 1370",
                            BirthDate = new DateOnly(1988, 5, 7),
                            Cuit = "20-88888888-9",
                            Email = "agustin@example.com",
                            FirstName = "Agustín",
                            LastName = "Molina",
                            Mobile = "+5491100000015"
                        },
                        new
                        {
                            ClientId = 16,
                            Address = "Mendoza 1480",
                            BirthDate = new DateOnly(1996, 7, 19),
                            Cuit = "27-80123456-7",
                            Email = "julieta@example.com",
                            FirstName = "Julieta",
                            LastName = "Castro",
                            Mobile = "+5491100000016"
                        },
                        new
                        {
                            ClientId = 17,
                            Address = "Entre Ríos 1590",
                            BirthDate = new DateOnly(1984, 3, 11),
                            Cuit = "20-99999999-0",
                            Email = "ramiro@example.com",
                            FirstName = "Ramiro",
                            LastName = "Navarro",
                            Mobile = "+5491100000017"
                        },
                        new
                        {
                            ClientId = 18,
                            Address = "San Juan 1700",
                            BirthDate = new DateOnly(1993, 9, 2),
                            Cuit = "27-81234567-5",
                            Email = "bianca@example.com",
                            FirstName = "Bianca",
                            LastName = "Rojas",
                            Mobile = "+5491100000018"
                        },
                        new
                        {
                            ClientId = 19,
                            Address = "Santiago 1810",
                            BirthDate = new DateOnly(1987, 2, 13),
                            Cuit = "20-12121212-3",
                            Email = "nicolas@example.com",
                            FirstName = "Nicolás",
                            LastName = "Vega",
                            Mobile = "+5491100000019"
                        },
                        new
                        {
                            ClientId = 20,
                            Address = "Jujuy 1920",
                            BirthDate = new DateOnly(1992, 11, 21),
                            Cuit = "27-82345678-3",
                            Email = "elena@example.com",
                            FirstName = "Elena",
                            LastName = "Acosta",
                            Mobile = "+5491100000020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
